$dir = (Split-Path -Parent $MyInvocation.MyCommand.Path)
$parentDir = (Split-Path -Parent $dir)
$fgColors = ("#ffffff00", "#ff00ff00")
$bgColors = ("#70ffffff", "#5affffff")
& "$parentDir\show-taskbarBarChart.ps1" -interval 1000 -barWidth 5 -chartAndGapWidths "30,-1,-1,30" -bgColors ($bgColors * 10) -fgColors ($fgColors * 10)
